version: '3.8'

services:
  evolution-go:
    image: marcelolimajw/evolution-go-chatwoot:latest
    container_name: evolution-go
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "4000:4000"
    environment:
      # Servidor
      SERVER_PORT: 4000
      CLIENT_NAME: "evolution"

      # Segurança (OBRIGATÓRIO)
      GLOBAL_API_KEY: "0417bf43b0a8969bd6685bcb49d783df"

      # Banco de Dados PostgreSQL (RECOMENDADO)
      POSTGRES_AUTH_DB: "postgresql://postgres:postgres@postgres:5432/evogo_auth?sslmode=disable"
      POSTGRES_USERS_DB: "postgresql://postgres:postgres@postgres:5432/evogo_users?sslmode=disable"
      DATABASE_SAVE_MESSAGES: "false"

      # Logs e Debug
      WADEBUG: "INFO"
      LOGTYPE: "console"
      LOG_DIRECTORY: "/app/logs"
      LOG_MAX_SIZE: "100"
      LOG_MAX_BACKUPS: "5"
      LOG_MAX_AGE: "30"
      LOG_COMPRESS: "true"

      # Conexão
      CONNECT_ON_STARTUP: "false"
      WEBHOOKFILES: "true"

      # Sistema
      OS_NAME: "Linux"

      # Eventos (Opcionais)
      WEBHOOK_URL: ""
      AMQP_URL: ""
      AMQP_GLOBAL_ENABLED: "false"
      NATS_URL: ""
      NATS_GLOBAL_ENABLED: "false"

      # Armazenamento de Mídia (Opcional)
      MINIO_ENABLED: "false"

      # Proxy (Opcional)
      PROXY_HOST: ""
      PROXY_PORT: ""
      PROXY_USERNAME: ""
      PROXY_PASSWORD: ""

      # Eventos
      EVENT_IGNORE_GROUP: "false"
      EVENT_IGNORE_STATUS: "true"

      # QR Code
      QRCODE_MAX_COUNT: "5"

      # Chatwoot Integration
      CHATWOOT_URL: "https://atendimento.kortexia.com.br"
      CHATWOOT_TOKEN: "3ztpi1WvRNnmkYZYCk6jFJvY"
      CHATWOOT_ACCOUNT_ID: "2"
      CHATWOOT_INBOX_ID: "6"

    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/server/ok" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

    volumes:
      - evolution_data:/app/dbdata
      - evolution_logs:/app/logs
    networks:
      - minha_rede
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: evolution-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - minha_rede

volumes:
  evolution_data:
    driver: local
  evolution_logs:
    driver: local
  postgres_data:
    driver: local

networks:
  minha_rede:
    name: minha_rede
    external: true
